//Exercise #1

When a Mule app starts, a connectivity test runs on components that need to connect to an external server, such as the HTTP or FTP connector. If the test fails, the default behavior is to log a warning message and continue with the app's deployment, instead of blocking the deployment.

You can modify this behavior by setting a number of reconnection attempts to try after an initial failure and by forcing the deployment to fail when all connection attempts fail. To do so, set the following properties:

* Fail Deployment (`failsDeployment`): Forces the deployment to fail if the connection fails and any configured reconnection attempts are exhausted.
* Reconnect (`reconnect`): Limits the number of reconnection attempts and the interval at which to execute them. 
    ** For example, you might set a count of five reconnection attempts at a frequency of every 4000 milliseconds (ms). Defaults to 2 reconnection attempts at a frequency of 2000ms:

[source,xml]
----
<http:request-config name="HTTP_Request_Config" doc:name="HTTP Request Config">
  <http:request-conection host="https://jsonplaceholder.typicode.com/posts" port="80">
    <reconnection failsDeployment="true">
      <reconnect frequency="4000" count="5"/>
    </reconnection>
  </http:request-connection>
</HTTP_Request_Config>
----

* Reconnect Forever (`reconnect-forever`): Attempts to reconnect at a given interval. 
    ** For example, every 4000 ms for as long as the app runs. Defaults to every 2000 ms. No value for count is specified, as there is no limit on the number of retries:
    
[source,xml]
----
<http:request-connection host="https://jsonplaceholder.typicode.com/posts" port="80">
  <reconnection>
    <reconnect-forever frequency="4000"/>
  </reconnection>
</http:request-connection>
----
